### ISSUE TITLE
disable from file?

### ISSUE THREAD

**Issue by gsuez** [vlasenkofedor/joomla_options#2]
Hi Pal,
I test your plugin, and work perctly, thanks!
I have a question; you tried to put a script in some file - index.php eg - to disable bootstrap, jquery and mootools?
In Joomla 3.3, I use:
<?php
// Remove Scripts
$doc = JFactory::getDocument();
unset($doc->_scripts[JURI::root(true) . '/media/system/js/mootools-more.js']);
unset($doc->_scripts[JURI::root(true) . '/media/system/js/mootools-core.js']);
unset($doc->_scripts[JURI::root(true) . '/media/jui/js/jquery.min.js']);
unset($doc->_scripts[JURI::root(true) . '/media/jui/js/bootstrap.min.js']);
?>

But no work...
Thanks again, best regards

**Comment by Poznakomlus** [comment]
Hi
No, I made simpler, declared the classes with identical names the first
I redefined classes
